### ISSUE TITLE
定义了typescript 但是不报错

### ISSUE THREAD

**Issue by hanwenbo** [banxi1988/wepy-todo-demo#1]
为什么呢，我故意传错数据格式也不报错

**Comment by codetalks-new** [comment]
@hanwenbo  请举例说明谢谢。

**Comment by hanwenbo** [comment]
@banxi1988  const todo : Todo = "xxxxxxxxxxxxxxx"    不报错

**Comment by hanwenbo** [comment]
@banxi1988 Todo我看你约束了   但是我实际跑的时候  赋值 并未报错

**Comment by codetalks-new** [comment]
@hanwenbo  
你还需要安装配置 tslint . 然后建议将 ts 代码写在单独的文件。
如果不是的话，安装一下 TSTint Vue 插件。
![image](https://user-images.githubusercontent.com/726774/40041560-ff8758ec-5850-11e8-9b55-2204cd9f48e5.png)

**Comment by hanwenbo** [comment]
@banxi1988 编辑器配置了  不过我发现wepy build --watch 还是能编译通过  编辑器现在是可以提示错误与了 谢谢啊  请问如何让 wepy build编译的时候 发现typescript错误的时候 不让它编译成功呢

**Comment by guojingwen** [comment]
wepy.config.js
这个里面并没有引用 ts相关的配置
